from AlexNet import *
from InceptionResNetV2 import *
from PreResNet import *
from ResNet import *
from VGG import *
from densenet_cifar import *
from Inception3 import *
from CifarResNeXt import *
from DARTSNet import *
from genotypes import *